apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: 2.4.1
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  ignoreDifferences:
    - group: ""
      kind: Service
      name: nginx-ingress-controller
      jsonPointers:
        - /status
        - /metadata/annotations
        - /metadata/managedFields
    - group: coordination.k8s.io
      kind: Lease
      name: nginx-ingress-leader-election
      namespace: ingress-nginx
      jsonPointers:
        - /metadata
        - /spec
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec
        - /status
        - /metadata/annotations
        - /metadata/managedFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true




